const { withAppBuildGradle } = require('@expo/config-plugins');

/**
 * Config plugin: inject a release signingConfig into the generated
 * android/app/build.gradle that reads the keystore from environment variables.
 *
 * Why a plugin and not a hand-edit: `android/` is gitignored and regenerated by
 * `expo prebuild` on every build, so any manual edit to build.gradle is wiped.
 * This plugin reapplies the change each prebuild.
 *
 * Behaviour is intentionally *conditional at Gradle eval time*:
 *   - When COPYPARTY_UPLOAD_STORE_FILE is set (CI release builds), the release
 *     buildType is signed with our upload keystore.
 *   - When it is absent (local dev, PR builds, and F-Droid's from-source build),
 *     the release buildType falls back to the debug keystore. F-Droid strips and
 *     re-signs with its own key regardless, so it must never depend on ours.
 *
 * Env vars consumed by the generated Gradle:
 *   COPYPARTY_UPLOAD_STORE_FILE      absolute path to the .keystore
 *   COPYPARTY_UPLOAD_STORE_PASSWORD  keystore password
 *   COPYPARTY_UPLOAD_KEY_ALIAS       key alias
 *   COPYPARTY_UPLOAD_KEY_PASSWORD    key password
 */
const RELEASE_SIGNING_CONFIG = `        release {
            // Populated only when the upload keystore env is present; otherwise
            // this config stays empty and the release buildType falls back to
            // debug signing (see below).
            if (System.getenv("COPYPARTY_UPLOAD_STORE_FILE")?.trim()) {
                storeFile file(System.getenv("COPYPARTY_UPLOAD_STORE_FILE"))
                storePassword System.getenv("COPYPARTY_UPLOAD_STORE_PASSWORD")
                keyAlias System.getenv("COPYPARTY_UPLOAD_KEY_ALIAS")
                keyPassword System.getenv("COPYPARTY_UPLOAD_KEY_PASSWORD")
            }
        }
`;

const RELEASE_SIGNING_SELECTOR =
  'signingConfig (System.getenv("COPYPARTY_UPLOAD_STORE_FILE")?.trim() ' +
  '? signingConfigs.release : signingConfigs.debug)';

function applyReleaseSigning(contents) {
  // Idempotency guard (and a no-op if the template ever changes shape).
  if (contents.includes('COPYPARTY_UPLOAD_STORE_FILE')) return contents;

  let next = contents;

  // 1) Add a `release { … }` block inside `signingConfigs { … }`.
  next = next.replace(/signingConfigs\s*\{/, (m) => `${m}\n${RELEASE_SIGNING_CONFIG}`);

  // 2) Point the release buildType at the release signing config when the env
  //    is present, else debug. The lazy match walks `buildTypes { … release {
  //    … }` so it targets the release buildType's signingConfig line, not the
  //    debug buildType's identical line above it.
  next = next.replace(
    /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/,
    `$1${RELEASE_SIGNING_SELECTOR}`,
  );

  return next;
}

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        `withReleaseSigning: expected a Groovy build.gradle, got ${cfg.modResults.language}`,
      );
    }
    const updated = applyReleaseSigning(cfg.modResults.contents);
    if (updated === cfg.modResults.contents && !updated.includes('COPYPARTY_UPLOAD_STORE_FILE')) {
      throw new Error(
        'withReleaseSigning: could not find signingConfigs/release buildType to patch — ' +
          'the android template may have changed.',
      );
    }
    cfg.modResults.contents = updated;
    return cfg;
  });
};

// Exported for unit testing of the pure string transform.
module.exports.applyReleaseSigning = applyReleaseSigning;
