const { withAndroidManifest, AndroidConfig } = require('@expo/config-plugins');

/**
 * Config plugin: set android:usesCleartextTraffic="true" on the <application>.
 *
 * Why: Android release builds default usesCleartextTraffic to false, so a release
 * APK can't reach plain http:// copyparty servers — every request fails with
 * "Network request failed". Dev/debug builds work only because Expo/RN set it
 * true in the *debug* manifest. copyparty is frequently deployed as plain http://
 * on a LAN, so the published app must allow cleartext. (https:// keeps working
 * either way.)
 *
 * Why a plugin and not a hand-edit: android/ is gitignored and regenerated by
 * `expo prebuild` on every build, so the AndroidManifest.xml change must flow
 * through a config plugin to survive — never hand-edit AndroidManifest.xml.
 */
function setUsesCleartextTraffic(androidManifest) {
  const app = AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);
  app.$['android:usesCleartextTraffic'] = 'true';
  return androidManifest;
}

module.exports = function withCleartextTraffic(config) {
  return withAndroidManifest(config, (cfg) => {
    cfg.modResults = setUsesCleartextTraffic(cfg.modResults);
    return cfg;
  });
};

// Exported for unit testing of the pure manifest transform.
module.exports.setUsesCleartextTraffic = setUsesCleartextTraffic;
