#!/usr/bin/env node
// Single source of truth for the app version lives in app.json:
//   expo.version          -> Android versionName / iOS short version (semver)
//   expo.android.versionCode -> Android versionCode (monotonic integer; the
//                               value F-Droid reads when it builds from source)
// package.json `version` is kept in sync purely for tooling hygiene.
//
// `android/` is generated by `expo prebuild`, so we never edit build.gradle —
// prebuild copies these values in. This script is the only sanctioned way to
// bump them so the three numbers can never drift.
//
// Usage:
//   node scripts/bump-version.mjs patch|minor|major   # bump semver + versionCode
//   node scripts/bump-version.mjs 1.4.0               # set semver, +1 versionCode
//   node scripts/bump-version.mjs --check v1.4.0      # assert tag matches app.json
//   node scripts/bump-version.mjs --print             # print current version
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const appJsonPath = join(root, 'app.json');
const pkgJsonPath = join(root, 'package.json');

const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'));
const writeJson = (p, obj) => writeFileSync(p, JSON.stringify(obj, null, 2) + '\n');

const SEMVER = /^(\d+)\.(\d+)\.(\d+)$/;

function bumpSemver(current, kind) {
  const m = SEMVER.exec(current);
  if (!m) throw new Error(`app.json version "${current}" is not plain semver`);
  let [major, minor, patch] = m.slice(1).map(Number);
  if (kind === 'major') (major += 1), (minor = 0), (patch = 0);
  else if (kind === 'minor') (minor += 1), (patch = 0);
  else if (kind === 'patch') patch += 1;
  else throw new Error(`unknown bump kind: ${kind}`);
  return `${major}.${minor}.${patch}`;
}

const arg = process.argv[2];
if (!arg) {
  console.error('usage: bump-version.mjs <patch|minor|major|X.Y.Z|--check vX.Y.Z|--print>');
  process.exit(2);
}

const app = readJson(appJsonPath);
const current = app.expo.version;
const currentCode = app.expo.android?.versionCode ?? 0;

if (arg === '--print') {
  console.log(`${current} (versionCode ${currentCode})`);
  process.exit(0);
}

if (arg === '--check') {
  const tag = process.argv[3] ?? '';
  const tagVersion = tag.replace(/^v/, '');
  if (tagVersion !== current) {
    console.error(
      `tag ${tag} (=> ${tagVersion}) does not match app.json version ${current}`,
    );
    process.exit(1);
  }
  console.log(`tag ${tag} matches app.json version ${current}`);
  process.exit(0);
}

const next = SEMVER.test(arg) ? arg : bumpSemver(current, arg);
const nextCode = currentCode + 1;

app.expo.version = next;
app.expo.android = { ...app.expo.android, versionCode: nextCode };
writeJson(appJsonPath, app);

const pkg = readJson(pkgJsonPath);
pkg.version = next;
writeJson(pkgJsonPath, pkg);

console.log(`version ${current} -> ${next}, versionCode ${currentCode} -> ${nextCode}`);
console.log('Next: commit, then `git tag v' + next + '` to trigger a release build.');
